import { Product, AgentProduct, CommercePolicy, Profile } from './types';

export const DEMO_SELLER: Profile = {
  id: 'seller-demo-001',
  role: 'seller',
  name: 'ApexTech Electronics',
  created_at: new Date().toISOString(),
};

export const DEMO_BUYER: Profile = {
  id: 'buyer-demo-001',
  role: 'buyer',
  name: 'Rohan Sharma',
  created_at: new Date().toISOString(),
};

export const DEMO_COMMERCE_POLICY: CommercePolicy = {
  id: 'policy-demo-001',
  seller_id: DEMO_SELLER.id,
  max_discount: 15.0, // max 15% discount
  max_quantity_per_order: 3,
  require_confirmation: true,
  max_auto_order_value: 15000.0,
  allow_ai_recommendations: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    seller_id: DEMO_SELLER.id,
    name: 'JBL Tune 770NC Wireless ANC Headphones',
    description: 'Over-ear wireless headphones with Active Noise Cancelling, 70-hour battery life, and speed charge in Black.',
    category: 'headphones',
    price: 5999,
    currency: 'INR',
    stock: 15,
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80',
    features: ['Active Noise Cancellation (ANC)', '70 Hours Battery Life', 'Bluetooth 5.3', 'Multi-point Connection'],
    delivery_info: { est_days: 2, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-002',
    seller_id: DEMO_SELLER.id,
    name: 'Cosmic Byte GS430 Gaming Headset',
    description: 'Budget wired gaming headset with 3D surround sound, flexible microphone, and RGB lighting for PC & PS5.',
    category: 'headphones',
    price: 1299,
    original_price: 999,
    currency: 'INR',
    stock: 24,
    image_url: 'https://images.unsplash.com/photo-1599669454699-24889d6df33b?w=500&q=80',
    features: ['3D Surround Sound', 'Flexible Noise Canceling Mic', 'RGB Lighting', '3.5mm Audio Jack'],
    delivery_info: { est_days: 3, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-003',
    seller_id: DEMO_SELLER.id,
    name: 'Boat Rockerz 450 Pro Wireless Headphones',
    description: 'On-ear bluetooth headset with 70H playback, ASAP Fast Charge, and 40mm drivers under 2000.',
    category: 'headphones',
    price: 1999,
    currency: 'INR',
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500&q=80',
    features: ['70 Hours Playback', 'ASAP Fast Charge', 'Bluetooth v5.0', 'Super Extra Bass'],
    delivery_info: { est_days: 2, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-004',
    seller_id: DEMO_SELLER.id,
    name: 'Logitech G304 Lightspeed Wireless Gaming Mouse',
    description: 'HERO Sensor 12,000 DPI, 250h battery life, lightweight 99g wireless gaming mouse in Matte Black.',
    category: 'gaming',
    price: 2799,
    currency: 'INR',
    stock: 12,
    image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=500&q=80',
    features: ['LIGHTSPEED Wireless 1ms', 'HERO Sensor 12k DPI', '250 Hours Battery', '6 Programmable Buttons'],
    delivery_info: { est_days: 2, free_shipping: true },
    return_policy: { returnable: true, days: 10 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-005',
    seller_id: DEMO_SELLER.id,
    name: 'Keychron K2 V2 Wireless Mechanical Keyboard',
    description: 'Compact 75% Layout Bluetooth Mechanical Keyboard with Gateron Brown Switches and RGB Backlighting.',
    category: 'keyboards',
    price: 7499,
    currency: 'INR',
    stock: 8,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&q=80',
    features: ['Wireless Bluetooth & Wired USB-C', '75% Compact Layout', 'Mac & Windows Compatible', 'RGB Backlight'],
    delivery_info: { est_days: 4, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-006',
    seller_id: DEMO_SELLER.id,
    name: 'Realme Buds Air 5 Pro TWS Earbuds',
    description: 'True wireless earbuds with 50dB Active Noise Cancellation, Hi-Res LDAC audio, and 40H total battery.',
    category: 'audio',
    price: 4999,
    currency: 'INR',
    stock: 18,
    image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80',
    features: ['50dB Smart ANC', 'Dual Drivers (11mm+6mm)', '40 Hours Playback', 'LDAC Hi-Res Audio'],
    delivery_info: { est_days: 2, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-007',
    seller_id: DEMO_SELLER.id,
    name: 'Anker PowerCore 20000mAh Power Bank',
    description: 'High capacity portable charger with 22.5W Fast Charging USB-C Power Delivery for smartphones & tablets.',
    category: 'accessories',
    price: 2499,
    currency: 'INR',
    stock: 0, // OUT OF STOCK FOR DEMO SCENARIO 1
    image_url: 'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=500&q=80',
    features: ['20000mAh Power Capacity', '22.5W Fast Charging', 'Dual USB Output', 'Trickle-Charging Mode'],
    delivery_info: { est_days: 3, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-008',
    seller_id: DEMO_SELLER.id,
    name: 'Noise ColorFit Pro 5 Smartwatch',
    description: '1.85" AMOLED display smartwatch with Bluetooth calling, SOS feature, 100+ sports modes, and IP68 rating.',
    category: 'wearables',
    price: 3499,
    currency: 'INR',
    stock: 20,
    image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80',
    features: ['1.85" AMOLED Display', 'Bluetooth Calling', 'SpO2 & Heart Rate Tracker', '7 Day Battery Life'],
    delivery_info: { est_days: 2, free_shipping: true },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
  {
    id: 'prod-009',
    seller_id: DEMO_SELLER.id,
    name: 'Portronics Ergofit Aluminium Laptop Stand',
    description: 'Foldable ergonomic laptop stand with 6 adjustable height angles, heat dissipation ventilation for 10-15.6" laptops.',
    category: 'accessories',
    price: 899,
    currency: 'INR',
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&q=80',
    features: ['Aluminium Alloy Construction', '6 Adjustable Heights', 'Non-Slip Silicone Pads', 'Foldable & Portable'],
    delivery_info: { est_days: 3, free_shipping: false },
    return_policy: { returnable: true, days: 7 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    is_ai_ready: true,
  },
];

export const INITIAL_AGENT_PRODUCTS: AgentProduct[] = INITIAL_PRODUCTS.map((prod) => ({
  id: `agent-prod-${prod.id}`,
  product_id: prod.id,
  seller_id: prod.seller_id,
  normalized_name: prod.name,
  normalized_category: prod.category.toLowerCase(),
  attributes: {
    wireless: prod.name.toLowerCase().includes('wireless') || prod.description.toLowerCase().includes('bluetooth'),
    anc: prod.features.some((f) => f.toLowerCase().includes('anc') || f.toLowerCase().includes('noise cancellation')),
    battery_hours: prod.features.find((f) => f.includes('Hours')) ? 70 : 30,
    price: prod.price,
    currency: prod.currency,
  },
  use_cases: prod.category === 'gaming' ? ['gaming', 'esports', 'pc'] : ['daily_use', 'travel', 'work'],
  search_terms: [prod.name.toLowerCase(), prod.category, ...prod.features.map((f) => f.toLowerCase())],
  structured_description: `${prod.name} (${prod.category}) priced at ₹${prod.price}. Key specs: ${prod.features.join(', ')}.`,
  agent_metadata: {
    wireless: prod.name.toLowerCase().includes('wireless'),
    anc: prod.features.some((f) => f.toLowerCase().includes('anc')),
    gaming_oriented: prod.category === 'gaming' || prod.name.toLowerCase().includes('gaming'),
    price_source: 'seller_database',
    inventory_source: 'seller_database',
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}));
